name: nexus_mods
version: 1.0.0
description: A library for interacting with the Nexus Mods API
homepage: https://github.com/ArcaneArts/nexus_mods
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  chopper: ^6.1.1
  json_annotation: ^4.8.0
dev_dependencies:
  build_runner: ^2.3.3
  chopper_generator: ^6.0.0
  json_serializable: ^6.6.1
  swagger_dart_code_generator: ^2.10.4
  test: ^1.3.0
